#!/usr/bin/env node

import meow from "meow";
import open from "open";
import { getText, storeText, urlShortner } from "./utils.js";

const cli = meow(
  `
  Usage
    $ tvault <command> [options]

  Commands
    shorten <url>           Shorten a URL (optionally with a custom key)
    store <text>            Store text with an autogenerated or custom key
    get <key>               Retrieve stored text or URL
    open <key>              Open a shortened URL in the browser

  Options
    --key, -k               Custom key for shorten/store
    --help                  Show help
    --version               Show version

  Examples
    $ tvault shorten https://google.com
    $ tvault shorten https://github.com -k gh
    $ tvault store "hello world"
    $ tvault store "notes here" --key note1
    $ tvault get note1
    $ tvault open gh
`,
  {
    importMeta: import.meta,
    flags: {
      key: {
        type: "string",
        shortFlag: "k",
      },
    },
  }
);
const [command,...args] =cli.input
const key = cli.flags.key;

switch(command){
    case "shorten": {
    const url = args[0];
    if (!url) {
      console.error("Please provide a URL to shorten.");
      break;
    }
    try {
      const shortUrl = await urlShortner(url, key);
      console.log("Shortened URL:", shortUrl);
    } catch (err) {
      console.error("Error:", err);
    }
    break;
  }
    case "store":{
        const text = args.join(" ");
        if(!text){
            console.error("Please provide text to store.");
            break
        }
        const message = await storeText(text,key!)
        console.log(message);
        break;
    }
    case "get":{
        let key = args[0];
        if(!key){
            console.error("Please provide a key to retrieve the stored text/URL.");
            break;
        }
        const text = await getText(key);
        console.log("Retrieved Text/URL:",text);
        break;
    }
    case "open":{
        const code=args[0];
        if(!code){
            console.error("Please provide a key to open the shortened URL.");
            break
        }
        const shortenedUrl = "https://t.mahs.me/u/"+code;
        console.log("Opening URL:",shortenedUrl);
        await open(shortenedUrl);
        break;
    }
    default:{
        console.error("Unknown command. Use --help to see available commands.");
        cli.showHelp(1);
    }
}